version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend 
    restart: always
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgresql://user:userpassword@postgres_flask:5432/flaskdb
      BACKEND_PORT: http://localhost:5000
    ports:
      - "5000:5000"
    depends_on:
      - postgres_flask


  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    environment:
      VITE_API_URL: http://backend:5000
    ports:
      - "5173:5173"
    depends_on:
      - backend

  postgres_flask:
    image: postgres:latest
    container_name: flask_db
    restart: always
    environment:
      POSTGRES_DB: flaskdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql 
  
volumes:
  postgres_data: